"""add rest timers to sets migration

Revision ID: 3a8fe13c6f7c
Revises: 1775c0a4eea7
Create Date: 2026-02-02 23:21:20.219496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8fe13c6f7c'
down_revision: Union[str, Sequence[str], None] = '1775c0a4eea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setdetails', sa.Column('rest_time', sa.Integer(), nullable=False, server_default='180000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setdetails', 'rest_time')
    # ### end Alembic commands ###
